### ISSUE TITLE
Suggest allow different version of custom Nextcloud server

### ISSUE THREAD

**Issue by samhei03** [saber-notes/saber#1056] opened 2023-12-14 11:03 UTC
### Motivation

Recently, the app only support connect with specific version of nextCloud (version 26). it is not allow the any other version (like: 28,27,25)

### Solution

Suggest allow Saber connects with different version of custom Nextcloud server.
Maybe just add a warning message, like the version maybe incompatible.

### Saber version

0.18.4

### Device

- Device: Galazy Tab S9
- OS: Android 14

- Device: iphone 14 pro
- OS: IOS 17.2

**Comment by samhei03** [comment] 2023-12-14 11:12
saber/lib/components/nextcloud/login_group.dart row:327

`class NcUnsupportedFailure implements LoginFailure {
  /// The Nextcloud version of the server
  final int? currentVersion;

  /// The Nextcloud version supported with the [nextcloud] package
  final int supportedVersion;

  NcUnsupportedFailure({
    required this.currentVersion,
    required this.supportedVersion,
  });

  @override
  late final String message = t.login.feedbacks.ncUnsupportedFailure(
    v: currentVersion ?? '?',
    s: supportedVersion,
  );
}`

**Comment by adil192** [comment] 2023-12-14 11:33
Duplicate of https://github.com/saber-notes/saber/issues/764

**Closed by adil192** 2023-12-14 11:33 UTC
Labels: enhancement
