### ISSUE TITLE
Apps won't sync with each other (Ipad and linux)

### ISSUE THREAD

**Issue by LeonardoCT** [saber-notes/saber#1306] opened 2024-07-07 22:21 UTC
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

I have both the linux version (flatpak) and the ipad os version
i'm using my own nextcloud server, and i can see files in the saber dir:
![image](https://github.com/saber-notes/saber/assets/20495117/d9ebfd91-f63b-4e44-a564-7605bcb4cdd3)
When i create a new file it happers in the nextcloud folder, but i can't see it in other clients eg: files created in the ipad app won't appear in the linux app and viceversa:
Linux app:
![image](https://github.com/saber-notes/saber/assets/20495117/963a40a4-9811-4d49-9ba4-88c00fe792e3)
ipad app:
<img width="1180" alt="Screenshot 2024-07-08 (00 12 17) jpeg" src="https://github.com/saber-notes/saber/assets/20495117/f42168d2-ba9b-4b84-a118-05b51deb1a42">

i've double checked and i'm using the same encryption password in both instances.

### To reproduce

1. create note on device 1
2. create note on device 2
3. See them appear on the nextcloud folder (they can successfully sync)
4. note that was created on device 1 won't appear on device 2 and viceversa

### Expected behavior

Beeing able to see and edit notes from both devices

### Saber version

Linux:
0.24.1
Ios:
0.24.1 (AppStore)

### Device
- Device 1 : Ipad 10
- OS: IpadOS 17.5.1

- Device 2 : my main desktop
- OS: Linux Mint 21.3

**Comment by Lennart01** [comment] 2024-07-08 15:12
Duplicate of #1304 
Try downgrading to [v0.23.3](https://github.com/saber-notes/saber/releases/tag/v0.23.3)

**Closed** 2024-07-20 20:46 UTC
Labels: bug
