### ISSUE TITLE
Option to turn off stylus button undo

### ISSUE THREAD

**Issue by pjaml** [saber-notes/saber#1115] opened 2024-01-29 21:43 UTC
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Motivation

Holding the stylus (S Pen) button and tapping the screen invokes undo. The problem is I frequently press this button accidentally, undoing whatever I'm in the process of writing. Also, sometimes when I hold the stylus button down intending to erase, it undoes instead because I haven't dragged the stylus or held it down on the screen long enough.

### Solution

I'd like there to be an option in the settings to turn off this "Hold stylus button and tap screen to undo" feature.

### Saber version

v0.19.2 F-Droid (19020)

### Device

- Device: Samsung Galaxy Tab S6 Lite
- OS: Android 13

### Anything else?

Saber keeps getting better and better, thanks for making this app!

**Comment by atahanacar** [comment] 2024-01-30 01:02
Maybe related? #1006

**Comment by pjaml** [comment] 2024-01-30 19:00
> Maybe related #1006

I've noticed that issue too, but I think I'd still want this feature even if it gets fixed.

**Comment by atahanacar** [comment] 2024-03-26 17:44
@adil192 I will implement this if we can agree on specifics such as where on the settings page it will go. I think creating a separate section called "Stylus" would be acceptable, in case new options regarding stylus usage (like assigning tools to physical buttons) are implemented.

**Comment by Polux49** [comment] 2024-04-30 15:57
Is this particular to stylus? It seems simlar (related?) to the "undesirable undo with two finger" bug https://github.com/saber-notes/saber/issues/643.

**Comment by atahanacar** [comment] 2024-05-03 21:16
> Is this particular to stylus?

Yes it is. The issue you mentioned is actually a bug caused (I think after a quick skim) by a feature that's supposed to prevent accidental strokes when zooming. This issue is a feature request that is asking to add an option to disable a feature.

**Comment by adil192** [comment] 2024-06-17 07:40
There is no such feature, just a bug causing an undo.
Closing as duplicate of #1006

**Closed by adil192** 2024-06-17 07:40 UTC
Labels: bug, duplicate
