### ISSUE TITLE
Can't draw rectangles

### ISSUE THREAD

**Issue by abulusky** [saber-notes/saber#1174] opened 2024-03-15 11:08 UTC
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

Saber apparently hates rectangles. Squares are fine though. but trying to draw a long rectangle results in circle.

### To reproduce

Try to draw a long rectangle

### Expected behavior

Should draw long rectangles, not circles.

### Saber version

0.21.1

### Device

- OS: Android

### Anything else?

https://github.com/saber-notes/saber/assets/130356304/14a18294-c59c-4698-b92c-03fa3c326d79

**Comment by QubaB** [comment] 2024-03-15 16:33
This is probably caused by bug in https://github.com/adil192/one_dollar_unistroke_recognizer

I actually created a fix for this in https://github.com/adil192/one_dollar_unistroke_recognizer/pull/4

**Closed** 2024-03-15 17:45 UTC
Labels: bug

**Comment by IsotoxalDev** [comment] 2024-07-16 15:57
I am stil getting this issue on 24.1 version 
https://github.com/user-attachments/assets/07af4333-fe8b-47d3-860e-c974e81a7be8
