### ISSUE TITLE
S-Pen Undo Action Bug

### ISSUE THREAD

**Issue by MuradMathematics** [saber-notes/saber#1092] opened 2024-01-03 20:41 UTC
### Describe the bug

I am using an S-Pen with my Galaxy Tablet. The pen has a button on the side. Right now I found the following two actions useful:

- Drawing over the notes while holding the button works like an eraser.
- Tapping on the canvas once while the button is held down acts as an undo of the last drawn pen stroke

However, after utilizing the tapping behavior and wanting to continue drawing, the app goes into erasing mode.

### To reproduce

1. Draw some lines with the pen
2. Tap with the pen on the canvas while holding down the S-Pen's side button to undo certain strokes
3.  Now, without the pen touching the screen, release the S-Pen side button (after undoing we would like to continue with taking notes)
4. With the button now released, put the pen onto the screen. It will go into eraser mode and stay in there, until you lift the pen's tip from the screen again.

### Expected behavior

I would not expect the app to go into erasing mode - especially since no button is held down. I would expect to continue writing normally after having undone some strokes with the tapping action. This is especially annoying since it deletes parts which would require an undo again, like an endless cycle. 

### Saber version

v0.19.0 F-Droid (19000)

### Device

- Device: Samsung Galaxy S8+
- OS: Android 14

### Anything else?

The option "Automatically switch out eraser" in the options menu does not seem to be the issue here. The bug is present both with the option enabled and disabled.

**Comment by droghio** [comment] 2024-01-04 07:47
I can reproduce this with an Amazon Fire Max 11 tablet and its pen (which also has 1 button). Same issue, namely using the tap to undo feature locks the pen into erase mode until I remove the pen and tap the screen again.

OS: FireOS 8.3.2.1 (Android 11)
Saber Version: v0.19.0 F-Droid

**Comment by ZebraVogel94349** [comment] 2024-01-06 17:48
This is a duplicate of #1006 .

**Comment by adil192** [comment] 2024-06-17 07:39
Closing as duplicate of #1006

**Closed by adil192** 2024-06-17 07:39 UTC
Labels: bug
