### ISSUE TITLE
Pen does not work on Windows

### ISSUE THREAD

**Issue by DauerndamProgrammieren** [saber-notes/saber#1280] opened 2024-06-03 13:26 UTC
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

I can not write with my pen in the app on Windows 11. (Surface Slim Pen 2 + Surface Pro 8)

### To reproduce

Use a pen on windows. (Maybe only my setup is having this issue)

### Expected behavior

I expected to be able to write not only with my finger but also with my pen.

### Saber version

v 0.23.2

### Device

- Device: Surface Pro 8 (i5, 8gb RAM)
- OS: Windows 11 Home

**Comment by adil192** [comment] 2024-06-25 01:07
Duplicate of https://github.com/saber-notes/saber/issues/671#issuecomment-1567626366

**Closed by adil192** 2024-06-25 01:07 UTC
Labels: bug
