### ISSUE TITLE
switch the font 

### ISSUE THREAD

**Issue by biansty** [saber-notes/saber#1150] opened 2024-03-01 06:54 UTC
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Motivation

I want it to be able to switch the font of the text so that I can display the text in my imported font

### Solution

I want it to be able to switch the font of the text so that I can display the text in my imported font

### Saber version

v0.20.2 F-Droid(20020)

### Device

- Device:VIVO S9
- OS:Android 13

**Comment by ZebraVogel94349** [comment] 2024-03-01 10:51
This is a duplicate of #488 .

**Comment by adil192** [comment] 2024-06-25 01:18
Duplicate of https://github.com/saber-notes/saber/issues/488

**Closed by adil192** 2024-06-25 01:18 UTC
Labels: enhancement
