### ISSUE TITLE
An option for infinite canvas note-taking?

### ISSUE THREAD

**Issue by GurrenLagann114** [saber-notes/saber#1089] opened 2024-01-02 13:19 UTC
### Motivation

An infinite canvas mode would be nice to write mental maps and making schemes.

### Solution

The closest inspiration I'm thinking about would be OneNote, with a very large board that's basically infinite.

### Saber version

v0.19.0 (19000)

### Device

- Device: Tab S8+
- OS: Android 14

**Comment by ZebraVogel94349** [comment] 2024-01-06 17:40
This is a duplicate of #88 .

**Comment by GurrenLagann114** [comment] 2024-01-06 17:46
Ok, rather than pointing out useless details (because I was certainly not going to look through 1000 issues) could I know if it is at least possible, since no answer was provided here nor on #88?

**Comment by adil192** [comment] 2024-01-06 18:10
Yes it's technically feasible. No I'm not implementing it right now. Closing as duplicate of #88.

**Closed by adil192** 2024-01-06 18:10 UTC
Labels: enhancement

**Comment by GurrenLagann114** [comment] 2024-01-06 18:13
> Yes it's technically feasible.

👍
