### ISSUE TITLE
Sync doesn't work between Linux and Android

### ISSUE THREAD

**Issue by AtiusAmy** [saber-notes/saber#994] opened 2023-11-02 07:39 UTC
### Describe the bug

Sync doesn't work between Linux and Android

### To reproduce

1. Sign into Nextcloud on both Linux and Android devices
2. Makes note
3. Sees that it does not sync

### Expected behavior

1. Sign into Nextcloud on both Linux and Android devices
2. Makes note
3. Sync with eachother

### Saber version

v0.17.1 DIRTY, v0.17.0 F-Droid

### Device

- Device: Lenovo Ideapad 14IAU7
- OS: Fedora Silverblue

-Device: Xiaomi Mi Pad 5
- OS: MIUI for Pad

**Comment by Iey4iej3** [comment] 2023-11-03 14:11
Is it due to https://github.com/saber-notes/saber/issues/945?

**Comment by adil192** [comment] 2023-11-03 23:31
Closing as duplicate of #945

**Closed by adil192** 2023-11-03 23:31 UTC
Labels: bug, duplicate
