### ISSUE TITLE
Infinite Canvas Feature

### ISSUE THREAD

**Issue by yubikku** [saber-notes/saber#1055] opened 2023-12-14 10:18 UTC
### Motivation

Thank you for the app and taking the initiative to make a Libre Notes Apps. I would like an infinite canvas feature similar to the `squid` app. I base my note taking system as such in this YouTube video: https://www.youtube.com/watch?v=ntaO3-n-isc , where it dwells on the idea of a free form note taking system.

Although zooming in and using the S-pen is still janky to take notes with. The page per page basis still seems limiting in how much I could do this free form note taking.

### Solution

Add Infinite Canvas Feature, can be an option in the '+' menu, under or above `New note`.
The infinite canvas system is kinda like Excalidraw or draw.io

### Alternatives

Could be a seperate appif its difficult to integrate with the base app itself.

### Saber version

v0.18.4 F-Droid (18040)

### Device

- Device: Samsung S6 Lite
- OS: Lineage OS 20 / Android 13

**Comment by adil192** [comment] 2023-12-14 11:35
Duplicate of https://github.com/saber-notes/saber/issues/88

**Closed by adil192** 2023-12-14 11:35 UTC
Labels: enhancement
