### ISSUE TITLE
Save whiteboard to notes

### ISSUE THREAD

**Issue by alr86** [saber-notes/saber#1283] opened 2024-06-05 13:15 UTC
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Motivation

Sometimes I want to save something that I wrote on the whiteboard but can't.

### Solution
Add an option to save the whiteboard content in notes."

### Saber version

0.23.1

**Comment by ZebraVogel94349** [comment] 2024-06-06 06:52
This is a duplicate of #344 
As a workaround you can export the whiteboard as a .sba file, rename it to something else and reimport it.

**Closed** 2024-06-08 06:56 UTC
Labels: enhancement
